#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const vm = require("node:vm");

const outputPath = process.argv[2] || "SUMMARY_REVIEW.md";

const noopElement = {
  open: false,
  hidden: false,
  classList: { toggle() {} },
  dataset: {},
  style: { setProperty() {} },
  addEventListener() {},
  close() {},
  showModal() {},
  appendChild() {},
  remove() {},
  click() {},
  querySelectorAll() { return []; },
  getBoundingClientRect() { return { left: 0, top: 0, width: 960, height: 600 }; },
  getContext() {
    return {
      clearRect() {}, fillRect() {}, beginPath() {}, moveTo() {}, lineTo() {}, arcTo() {},
      closePath() {}, fill() {}, stroke() {}, arc() {}, fillText() {},
      set fillStyle(_value) {}, set strokeStyle(_value) {}, set lineWidth(_value) {},
      set lineCap(_value) {}, set font(_value) {}, set textAlign(_value) {},
    };
  },
  set innerHTML(_value) {},
  get innerHTML() { return ""; },
  set textContent(_value) {},
  get textContent() { return ""; },
};

function loadAppContext() {
  const context = {
    console,
    Blob,
    window: { clearTimeout() {}, setTimeout() {} },
    URL: { createObjectURL() { return "blob:test"; }, revokeObjectURL() {} },
    navigator: { clipboard: { writeText() {} } },
    requestAnimationFrame() {},
    document: {
      addEventListener() {},
      createElement() { return noopElement; },
      body: { appendChild() {} },
      querySelectorAll() { return []; },
      querySelector() { return noopElement; },
      getElementById() { return noopElement; },
    },
  };
  vm.createContext(context);
  vm.runInContext(fs.readFileSync("app.js", "utf8"), context);
  return context;
}

function main() {
  const context = loadAppContext();
  const summaries = vm.runInContext(`
(() => {
  const CASES = [
    {
      name: "Low-signal wanderer",
      evidence: { social_drive: 0.16, novelty_breadth: 0.10 },
      events: 4,
    },
    {
      name: "Social reader",
      evidence: { social_prediction_uncertainty: 0.18, social_monitoring_cost: 0.20, masking_adaptation: 0.08 },
      events: 5,
    },
    {
      name: "Sensory-only regulator",
      evidence: { sensory_accumulation: 0.32, regulation_dependency: 0.34 },
      events: 6,
    },
    {
      name: "Quiet pattern-maker",
      evidence: {
        sensory_accumulation: 0.18,
        regulation_dependency: 0.20,
        focused_loop_depth: 0.20,
        systemizing_structure: 0.20,
        ambiguity_avoidance: 0.10,
      },
      events: 7,
    },
    {
      name: "Female-presentation core",
      evidence: {
        social_prediction_uncertainty: 0.16,
        social_monitoring_cost: 0.18,
        masking_adaptation: 0.14,
        sensory_accumulation: 0.22,
        regulation_dependency: 0.24,
        focused_loop_depth: 0.20,
        systemizing_structure: 0.22,
        ambiguity_avoidance: 0.16,
        context_switch_friction: 0.08,
      },
      events: 8,
    },
    {
      name: "Imaginative maker",
      evidence: { imagination_play: 0.36, novelty_breadth: 0.08, focused_loop_depth: 0.04 },
      events: 5,
    },
  ];

  return CASES.map((testCase) => {
    model = createModel();
    model.simulatedEventCount = testCase.events;
    applyDelta(model.evidence, testCase.evidence);
    const profile = currentProfile();
    const axis = axisResult(profile);
    const shownScore = displayScore(axis);
    const drivers = signalDrivers(profile);
    return {
      name: testCase.name,
      profileName: playProfileName(profile),
      band: profile.band,
      score100: shownScore.score,
      range: [shownScore.low, shownScore.high],
      confidence: profile.credibility.confidence,
      drivers,
      meaning: scoreMeaningText(profile, drivers),
      plainRead: plainReadText(profile, drivers),
      narrative: profileNarrative(profile),
      flags: profile.flags,
      credibilityFlags: profile.credibility.flags,
    };
  });
})()
`, context);

  const markdown = [
    "# Lantern Tide Summary Review",
    "",
    "Generated by `node summary_review.js`.",
    "",
    "These are synthetic wording checks. They help catch confusing or overclaiming summaries; they are not validation data.",
    "",
    ...summaries.map((item) => [
      `## ${item.name}`,
      "",
      `**Profile:** ${item.profileName}`,
      `**Lantern Tide score:** ${item.score100}/100`,
      `**Likely range:** ${item.range[0]}-${item.range[1]}`,
      `**Confidence:** ${item.confidence}`,
      `**Band:** ${item.band}`,
      "",
      item.meaning,
      "",
      `Mostly driven by: ${item.drivers.join(", ")}.`,
      "",
      item.plainRead,
      "",
      "Route wording:",
      ...item.narrative.map((line) => `- ${line}`),
      "",
      item.flags.length ? `Flags: ${item.flags.join(", ")}` : "Flags: none",
      item.credibilityFlags.length ? `Credibility notes: ${item.credibilityFlags.join(", ")}` : "Credibility notes: none",
      "",
    ].join("\n")),
  ].join("\n");

  fs.writeFileSync(outputPath, markdown);
  console.log(JSON.stringify({ outputPath, summaries }, null, 2));
}

main();
