#!/usr/bin/env python3
"""Autonomous multiband evaporator with a spin-droplet spectrum.

The droplet internal spectrum is generated by a transverse-field Ising-like
Hamiltonian on the L x L droplet.  Shell erosion is defined in the site basis
and then transformed into the spin-energy eigenbasis.
"""
from __future__ import annotations

import argparse
import csv
import pathlib
from dataclasses import dataclass

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from numpy.typing import NDArray

from scan_bose_hubbard_dos import DATADIR


@dataclass(frozen=True)
class Stage:
    k: int
    L: int
    core_dim: int
    rad_dim: int
    energy: float
    eigvals: NDArray[np.float64]
    eigvecs: NDArray[np.float64]


@dataclass(frozen=True)
class BasisState:
    stage: int
    eig: int
    rad_label: int
    hard_mask: int


def parse_float_list(value: str) -> list[float]:
    return [float(part.strip()) for part in value.split(",") if part.strip()]


def popcount(value: int) -> int:
    return int(value.bit_count())


def occupied(mask: int, mode: int) -> bool:
    return bool(mask & (1 << mode))


def mode_index(band: int, pos: int, chain_length: int) -> int:
    return band * chain_length + pos


def mode_band(mode: int, chain_length: int) -> int:
    return mode // chain_length


def mode_pos(mode: int, chain_length: int) -> int:
    return mode % chain_length


def add_mode(mask: int, mode: int) -> int:
    return mask | (1 << mode)


def move_mode(mask: int, src: int, dst: int) -> int:
    return (mask & ~(1 << src)) | (1 << dst)


def hard_masks(n_modes: int, max_quanta: int) -> list[int]:
    return [mask for mask in range(1 << n_modes) if popcount(mask) <= max_quanta]


def hard_energy(mask: int, bands: list[float], chain_length: int) -> float:
    total = 0.0
    for mode in range(len(bands) * chain_length):
        if occupied(mask, mode):
            total += bands[mode_band(mode, chain_length)]
    return total


def bit_spin(index: int, bit: int) -> int:
    return 1 if (index & (1 << bit)) else -1


def grid_edges(L: int) -> list[tuple[int, int]]:
    edges = []
    for y in range(L):
        for x in range(L):
            i = y * L + x
            if x + 1 < L:
                edges.append((i, y * L + x + 1))
            if y + 1 < L:
                edges.append((i, (y + 1) * L + x))
    return edges


def spin_hamiltonian(L: int, args: argparse.Namespace) -> NDArray[np.float64]:
    n = L * L
    dim = 1 << n
    hmat = np.zeros((dim, dim), dtype=float)
    rng = np.random.default_rng(args.seed + 17 * L)
    fields = args.h_field + args.random_field * rng.normal(size=n)
    edges = grid_edges(L)
    for state in range(dim):
        diag = 0.0
        for i in range(n):
            diag += fields[i] * bit_spin(state, i)
        for i, j in edges:
            diag += args.j_zz * bit_spin(state, i) * bit_spin(state, j)
        hmat[state, state] = diag
        for i in range(n):
            flipped = state ^ (1 << i)
            hmat[flipped, state] += args.lambda_x
    return 0.5 * (hmat + hmat.T)


def scaled_eigensystem(L: int, args: argparse.Namespace) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    hmat = spin_hamiltonian(L, args)
    eigvals, eigvecs = np.linalg.eigh(hmat)
    eigvals = eigvals - float(np.mean(eigvals))
    std = float(np.std(eigvals))
    if std > 1e-12:
        eigvals = eigvals * (args.internal_std / std)
    return eigvals, eigvecs


def build_stages(args: argparse.Namespace) -> list[Stage]:
    total_dim = args.q ** (args.L0 * args.L0)
    stages = []
    for k, L in enumerate(range(args.L0, args.Lmin - 1, -1)):
        eigvals, eigvecs = scaled_eigensystem(L, args)
        core_dim = eigvals.size
        rad_dim = total_dim // core_dim
        stages.append(Stage(k, L, core_dim, rad_dim, 4.0 * args.sigma * L, eigvals, eigvecs))
    return stages


def combine_inner_shell(inner: int, shell: int, L: int) -> int:
    """Map inner (L-1)^2 bits and shell bits into an L^2 site-basis index."""
    inner_L = L - 1
    full = 0
    shell_bit = 0
    for y in range(L):
        for x in range(L):
            full_bit = y * L + x
            if x < inner_L and y < inner_L:
                inner_bit = y * inner_L + x
                if inner & (1 << inner_bit):
                    full |= 1 << full_bit
            else:
                if shell & (1 << shell_bit):
                    full |= 1 << full_bit
                shell_bit += 1
    return full


def shell_overlap_terms(
    prev: Stage, nxt: Stage, args: argparse.Namespace
) -> list[list[tuple[int, int, float]]]:
    """Largest site-basis shell-removal overlaps for each old eigenstate."""
    shell_dim = nxt.rad_dim // prev.rad_dim
    out: list[list[tuple[int, int, float]]] = []
    for old_eig in range(prev.core_dim):
        candidates = []
        old_vec = prev.eigvecs[:, old_eig]
        for new_eig in range(nxt.core_dim):
            new_vec = nxt.eigvecs[:, new_eig]
            for shell in range(shell_dim):
                amp = 0.0
                for inner in range(nxt.core_dim):
                    full = combine_inner_shell(inner, shell, prev.L)
                    amp += new_vec[inner] * old_vec[full]
                if abs(amp) > args.overlap_cutoff:
                    candidates.append((new_eig, shell, float(amp)))
        candidates.sort(key=lambda item: abs(item[2]), reverse=True)
        out.append(candidates[: args.overlap_degree])
    return out


def thermal_target(bands: list[float], temperature: float) -> NDArray[np.float64]:
    weights = np.exp(-np.asarray(bands, dtype=float) / max(temperature, 1e-12))
    return weights / np.sum(weights)


def total_variation(p: NDArray[np.float64], q: NDArray[np.float64]) -> float:
    return float(0.5 * np.sum(np.abs(p - q)))


def build_basis(stages: list[Stage], masks: list[int]) -> tuple[list[BasisState], dict[BasisState, int]]:
    basis = [
        BasisState(stage.k, eig, rad, mask)
        for stage in stages
        for eig in range(stage.core_dim)
        for rad in range(stage.rad_dim)
        for mask in masks
    ]
    return basis, {state: idx for idx, state in enumerate(basis)}


def build_hamiltonian(
    args: argparse.Namespace,
    stages: list[Stage],
    basis: list[BasisState],
    index: dict[BasisState, int],
    masks: list[int],
    bands: list[float],
) -> sp.csr_matrix:
    rows: list[int] = []
    cols: list[int] = []
    data: list[complex] = []
    n_modes = len(bands) * args.chain_length

    for idx, state in enumerate(basis):
        stage = stages[state.stage]
        energy = stage.energy + stage.eigvals[state.eig] + hard_energy(state.hard_mask, bands, args.chain_length)
        rows.append(idx)
        cols.append(idx)
        data.append(energy)

    for state in basis:
        col = index[state]
        for mode in range(n_modes):
            if not occupied(state.hard_mask, mode):
                continue
            band = mode_band(mode, args.chain_length)
            pos = mode_pos(mode, args.chain_length)
            for delta in (-1, 1):
                new_pos = pos + delta
                if not (0 <= new_pos < args.chain_length):
                    continue
                target_mode = mode_index(band, new_pos, args.chain_length)
                if occupied(state.hard_mask, target_mode):
                    continue
                target = BasisState(
                    state.stage,
                    state.eig,
                    state.rad_label,
                    move_mode(state.hard_mask, mode, target_mode),
                )
                row = index.get(target)
                if row is None:
                    continue
                rows.append(row)
                cols.append(col)
                data.append(-args.chain_hop)

    overlaps = {
        prev.k: shell_overlap_terms(prev, nxt, args)
        for prev, nxt in zip(stages[:-1], stages[1:])
    }
    for prev, nxt in zip(stages[:-1], stages[1:]):
        shell_dim = nxt.rad_dim // prev.rad_dim
        for old_eig in range(prev.core_dim):
            source_base_energy = prev.energy + prev.eigvals[old_eig]
            for rad in range(prev.rad_dim):
                for mask in masks:
                    if popcount(mask) >= args.max_quanta:
                        continue
                    source = BasisState(prev.k, old_eig, rad, mask)
                    col = index[source]
                    for band, omega in enumerate(bands):
                        local_mode = mode_index(band, 0, args.chain_length)
                        if occupied(mask, local_mode):
                            continue
                        target_mask = add_mode(mask, local_mode)
                        for new_eig, shell, overlap in overlaps[prev.k][old_eig]:
                            new_rad = shell * prev.rad_dim + rad
                            if new_rad >= nxt.rad_dim or shell >= shell_dim:
                                continue
                            target_energy = nxt.energy + nxt.eigvals[new_eig] + omega
                            detuning = source_base_energy - target_energy
                            envelope = np.exp(-0.5 * (detuning / args.detuning_width) ** 2)
                            val = args.erosion_coupling * overlap * envelope
                            if abs(val) <= args.matrix_cutoff:
                                continue
                            target = BasisState(nxt.k, new_eig, new_rad, target_mask)
                            row = index[target]
                            rows.append(row)
                            cols.append(col)
                            data.append(val)
                            rows.append(col)
                            cols.append(row)
                            data.append(val)

    return sp.coo_matrix((data, (rows, cols)), shape=(len(basis), len(basis))).tocsr()


def initial_state(
    args: argparse.Namespace,
    stages: list[Stage],
    basis_index: dict[BasisState, int],
) -> NDArray[np.complex128]:
    rng = np.random.default_rng(args.seed + 10_000)
    top = stages[0]
    candidates = [
        eig for eig, value in enumerate(top.eigvals)
        if abs(float(value) - args.initial_internal_energy) <= args.initial_energy_window
    ]
    if not candidates:
        candidates = list(range(top.core_dim))
    psi = np.zeros(len(basis_index), dtype=np.complex128)
    if args.initial_state == "basis":
        psi[basis_index[BasisState(0, candidates[0], 0, 0)]] = 1.0
    elif args.initial_state == "haar":
        raw = rng.normal(size=len(candidates)) + 1j * rng.normal(size=len(candidates))
        raw /= np.sqrt(float(np.vdot(raw, raw).real))
        for eig, amp in zip(candidates, raw):
            psi[basis_index[BasisState(0, eig, 0, 0)]] = amp
    else:
        raise ValueError(f"unknown initial state: {args.initial_state}")
    return psi


def entropy_from_eigs(eigs: NDArray[np.float64]) -> float:
    vals = eigs[eigs > 1e-14]
    return float(-np.sum(vals * np.log(vals))) if vals.size else 0.0


def renyi2_from_eigs(eigs: NDArray[np.float64]) -> float:
    return float(-np.log(max(float(np.sum(eigs * eigs)), 1e-300)))


def core_rad_entropy(
    psi: NDArray[np.complex128],
    stages: list[Stage],
    basis: list[BasisState],
    masks: list[int],
) -> tuple[float, float]:
    mask_index = {mask: idx for idx, mask in enumerate(masks)}
    core_offsets = []
    rad_offsets = []
    core_total = 0
    rad_total = 0
    for stage in stages:
        core_offsets.append(core_total)
        rad_offsets.append(rad_total)
        core_total += stage.core_dim
        rad_total += stage.rad_dim
    coeff = np.zeros((core_total, rad_total * len(masks)), dtype=np.complex128)
    for amp, state in zip(psi, basis):
        if abs(amp) <= 1e-14:
            continue
        row = core_offsets[state.stage] + state.eig
        col = (rad_offsets[state.stage] + state.rad_label) * len(masks) + mask_index[state.hard_mask]
        coeff[row, col] += amp
    rho = coeff @ coeff.conj().T
    eigs = np.clip(np.linalg.eigvalsh(rho).real, 0.0, 1.0)
    return entropy_from_eigs(eigs), renyi2_from_eigs(eigs)


def observables(
    psi: NDArray[np.complex128],
    hmat: sp.csr_matrix,
    stages: list[Stage],
    basis: list[BasisState],
    masks: list[int],
    bands: list[float],
    args: argparse.Namespace,
) -> dict[str, float | str]:
    probs = np.abs(psi) ** 2
    stage_probs = np.zeros(len(stages), dtype=float)
    band_counts = np.zeros(len(bands), dtype=float)
    pos_counts = np.zeros(args.chain_length, dtype=float)
    mean_l = 0.0
    mean_quanta = 0.0
    hard_e = 0.0
    spin_e = 0.0
    for p, state in zip(probs, basis):
        stage = stages[state.stage]
        stage_probs[state.stage] += p
        mean_l += p * stage.L
        spin_e += p * stage.eigvals[state.eig]
        for mode in range(len(bands) * args.chain_length):
            if occupied(state.hard_mask, mode):
                band = mode_band(mode, args.chain_length)
                pos = mode_pos(mode, args.chain_length)
                band_counts[band] += p
                pos_counts[pos] += p
                mean_quanta += p
                hard_e += p * bands[band]
    band_probs = band_counts / mean_quanta if mean_quanta > 1e-12 else np.ones(len(bands)) / len(bands)
    temp = 2.0 * args.sigma / (max(mean_l, 1e-12) * np.log(args.q))
    target = thermal_target(bands, temp)
    entropy, renyi2 = core_rad_entropy(psi, stages, basis, masks)
    h_expect = complex(np.vdot(psi, hmat @ psi))
    return {
        "mean_L": float(mean_l),
        "mean_spin_energy": float(spin_e),
        "mean_quanta": float(mean_quanta),
        "hard_energy": float(hard_e),
        "temperature_proxy": float(temp),
        "band_tv_to_thermal": total_variation(band_probs, target),
        "band_probs": ";".join(f"{p:.8g}" for p in band_probs),
        "thermal_band_target": ";".join(f"{p:.8g}" for p in target),
        "chain_far": float(np.sum(pos_counts[max(1, args.chain_length // 2) :])),
        "core_radiation_entropy": entropy,
        "core_radiation_renyi2": renyi2,
        "hamiltonian_energy": float(h_expect.real),
        **{f"p_stage_{idx}": float(value) for idx, value in enumerate(stage_probs)},
    }


def summarize(rows: list[dict[str, float | str]]) -> dict[str, float | str]:
    final = rows[-1]
    hvals = [float(row["hamiltonian_energy"]) for row in rows]
    hard = [float(row["hard_energy"]) for row in rows]
    return {
        "case": final["case"],
        "basis_dim": final["basis_dim"],
        "bands": final["bands"],
        "chain_length": final["chain_length"],
        "final_mean_L": final["mean_L"],
        "final_p_final_stage": final.get("p_stage_2", 0.0),
        "max_p_final_stage": max(float(row.get("p_stage_2", 0.0)) for row in rows),
        "final_hard_energy": final["hard_energy"],
        "max_hard_energy": max(hard),
        "final_band_tv_to_thermal": final["band_tv_to_thermal"],
        "min_band_tv_to_thermal": min(float(row["band_tv_to_thermal"]) for row in rows),
        "final_band_probs": final["band_probs"],
        "final_thermal_target": final["thermal_band_target"],
        "final_core_radiation_entropy": final["core_radiation_entropy"],
        "final_core_radiation_renyi2": final["core_radiation_renyi2"],
        "final_chain_far": final["chain_far"],
        "energy_drift": max(hvals) - min(hvals),
    }


def write_csv(path: pathlib.Path, rows: list[dict[str, float | str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = sorted({key for row in rows for key in row})
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def run(args: argparse.Namespace) -> tuple[list[dict[str, float | str]], dict[str, float | str]]:
    bands = parse_float_list(args.bands)
    stages = build_stages(args)
    masks = hard_masks(len(bands) * args.chain_length, args.max_quanta)
    basis, index = build_basis(stages, masks)
    hmat = build_hamiltonian(args, stages, basis, index, masks, bands)
    psi0 = initial_state(args, stages, index)
    times = np.linspace(0.0, args.t_max, args.time_points)
    rows: list[dict[str, float | str]] = []
    for time, psi in zip(
        times,
        spla.expm_multiply((-1j) * hmat, psi0, start=0.0, stop=args.t_max, num=args.time_points),
    ):
        rows.append(
            {
                "case": args.case_name,
                "time": float(time),
                "basis_dim": len(basis),
                "bands": args.bands,
                "chain_length": args.chain_length,
                **observables(psi, hmat, stages, basis, masks, bands, args),
            }
        )
    return rows, summarize(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run spin-spectrum multiband evaporator.")
    parser.add_argument("--case-name", default="spin_spectrum_main")
    parser.add_argument("--q", type=int, default=2)
    parser.add_argument("--sigma", type=float, default=1.0)
    parser.add_argument("--L0", type=int, default=3)
    parser.add_argument("--Lmin", type=int, default=1)
    parser.add_argument("--bands", default="2,3,4,5,6")
    parser.add_argument("--chain-length", type=int, default=2)
    parser.add_argument("--max-quanta", type=int, default=2)
    parser.add_argument("--chain-hop", type=float, default=1.0)
    parser.add_argument("--erosion-coupling", type=float, default=0.55)
    parser.add_argument("--detuning-width", type=float, default=0.75)
    parser.add_argument("--overlap-degree", type=int, default=16)
    parser.add_argument("--overlap-cutoff", type=float, default=1e-10)
    parser.add_argument("--h-field", type=float, default=0.25)
    parser.add_argument("--j-zz", type=float, default=0.20)
    parser.add_argument("--lambda-x", type=float, default=0.75)
    parser.add_argument("--random-field", type=float, default=0.07)
    parser.add_argument("--internal-std", type=float, default=2.0)
    parser.add_argument("--initial-internal-energy", type=float, default=-1.0)
    parser.add_argument("--initial-energy-window", type=float, default=0.75)
    parser.add_argument("--matrix-cutoff", type=float, default=1e-12)
    parser.add_argument("--initial-state", choices=["basis", "haar"], default="haar")
    parser.add_argument("--seed", type=int, default=2468)
    parser.add_argument("--t-max", type=float, default=60.0)
    parser.add_argument("--time-points", type=int, default=31)
    parser.add_argument(
        "--timeseries-csv",
        type=pathlib.Path,
        default=DATADIR / "autonomous_spin_spectrum_multiband_timeseries.csv",
    )
    parser.add_argument(
        "--summary-csv",
        type=pathlib.Path,
        default=DATADIR / "autonomous_spin_spectrum_multiband_summary.csv",
    )
    args = parser.parse_args(argv)
    rows, summary = run(args)
    write_csv(args.timeseries_csv, rows)
    write_csv(args.summary_csv, [summary])
    print(f"[spin-spectrum] wrote {args.timeseries_csv}")
    print(f"[spin-spectrum] wrote {args.summary_csv}")
    print(
        "dim={basis_dim} final_L={final_mean_L:.3f} p_final={final_p_final_stage:.3f} "
        "Ehard={final_hard_energy:.3f} TV={final_band_tv_to_thermal:.3f} "
        "drift={energy_drift:.2e}".format(**summary)
    )
    print(f"bands={summary['final_band_probs']} thermal={summary['final_thermal_target']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
