#!/usr/bin/env python3
"""Replace ideal sector rethermalization by Hamiltonian scrambling.

The energy-resolved sector model succeeds when each sector is explicitly mixed:

    p_n(a) -> P_n / dim H_n.

This script replaces that ideal map by a unistochastic map generated by an
intra-sector Hamiltonian:

    U_n(tau) = exp(-i K_n tau)
    p_n' = |U_n|^2 p_n.

The emission channel is still the same golden-rule sector channel.  The test is
whether a concrete K_n can preserve both acceleration and hard thermality.
"""
from __future__ import annotations

import argparse
import csv
import pathlib

import numpy as np
from numpy.typing import NDArray

try:
    import scipy.linalg as la
except Exception as exc:  # pragma: no cover
    raise SystemExit(f"SciPy is required: {exc}")

from area_register_rate_scan import initial_populations, observables, step_pops
from scan_bose_hubbard_dos import DATADIR
from sector_hamiltonian_energy_resolved import (
    build_energy_resolved_sectors,
    build_transition_data,
    parse_list,
)
from sector_hamiltonian_evaporator import (
    spectrum_observables,
    summarize_series,
    target_x_distribution,
    write_csv,
)


def random_symmetric(rng: np.random.Generator, dim: int) -> NDArray[np.float64]:
    raw = rng.normal(size=(dim, dim))
    mat = (raw + raw.T) / 2.0
    return mat / np.sqrt(float(dim))


def expander_adjacency(dim: int) -> NDArray[np.float64]:
    mat = np.zeros((dim, dim), dtype=float)
    if dim <= 1:
        return mat
    multipliers = [2, 3]
    for i in range(dim):
        for delta in (-1, 1):
            j = (i + delta) % dim
            mat[i, j] = 1.0
            mat[j, i] = 1.0
        for mult in multipliers:
            j = (mult * i + 1) % dim
            mat[i, j] = 1.0
            mat[j, i] = 1.0
    degree = np.maximum(np.sum(mat != 0.0, axis=0).mean(), 1.0)
    return mat / np.sqrt(float(degree))


def sparse_random_adjacency(
    rng: np.random.Generator,
    dim: int,
    degree: int,
) -> NDArray[np.float64]:
    mat = np.zeros((dim, dim), dtype=float)
    if dim <= 1:
        return mat
    for i in range(dim):
        candidates = rng.choice(dim, size=min(degree, dim), replace=False)
        for j in candidates:
            if i == j:
                continue
            weight = rng.normal()
            mat[i, j] += weight
            mat[j, i] += weight
    scale = np.sqrt(max(float(degree), 1.0))
    return mat / scale


def hamiltonian_mixer_matrix(
    *,
    dim: int,
    mixing_type: str,
    tau: float,
    seed: int,
    sparse_degree: int,
) -> NDArray[np.float64] | None:
    if mixing_type == "none":
        return None
    if mixing_type == "uniform":
        return np.full((dim, dim), 1.0 / float(dim), dtype=float)

    rng = np.random.default_rng(seed)
    if mixing_type == "dense":
        k_mat = random_symmetric(rng, dim)
    elif mixing_type == "expander":
        k_mat = expander_adjacency(dim)
    elif mixing_type == "sparse":
        k_mat = sparse_random_adjacency(rng, dim, sparse_degree)
    else:
        raise ValueError(f"unknown mixing type: {mixing_type}")

    evals, evecs = la.eigh(k_mat)
    phases = np.exp(-1j * tau * evals)
    unitary = (evecs.astype(np.complex128) * phases[None, :]) @ evecs.T
    transition = np.abs(unitary) ** 2
    transition /= np.maximum(np.sum(transition, axis=0, keepdims=True), 1e-300)
    return transition.astype(float)


def build_mixers(
    sectors,
    mixing_type: str,
    tau: float,
    seed: int,
    sparse_degree: int,
) -> dict[int, NDArray[np.float64] | None]:
    mixers = {}
    for n, sector in sectors.items():
        mixers[n] = hamiltonian_mixer_matrix(
            dim=sector.dim,
            mixing_type=mixing_type,
            tau=tau,
            seed=seed + 13_000 + 101 * n,
            sparse_degree=sparse_degree,
        )
    return mixers


def apply_mixers(pops, mixers) -> None:
    for n, mixer in mixers.items():
        if mixer is None:
            continue
        pops[n] = mixer @ pops[n]
        total = float(np.sum(pops[n]))
        if total > 0.0:
            pops[n] = np.maximum(pops[n], 0.0)


def sector_uniformity(pops) -> float:
    total = 0.0
    weight_total = 0.0
    for pop in pops.values():
        weight = float(np.sum(pop))
        if weight <= 0.0:
            continue
        uniform = np.full_like(pop, weight / len(pop))
        total += 0.5 * float(np.sum(np.abs(pop - uniform)))
        weight_total += weight
    return total / max(weight_total, 1e-300)


def run_case(
    args: argparse.Namespace,
    *,
    seed: int,
    operator: str,
    mass_law: str,
    mixing_type: str,
    tau: float,
) -> dict[str, float | int | str]:
    sectors = build_energy_resolved_sectors(
        n_min=args.n_min,
        n_max=args.n_max,
        q=args.q,
        alpha=args.alpha,
        mass_law=mass_law,
        width_x=args.width_x,
        dos=args.dos,
        seed=seed,
    )
    transitions = build_transition_data(
        sectors=sectors,
        q=args.q,
        operator=operator,
        seed=seed,
        pmax=args.pmax,
        x_min=args.x_min,
        x_max=args.x_max,
        ohmic_power=args.ohmic_power,
    )
    mixers = build_mixers(
        sectors,
        mixing_type=mixing_type,
        tau=tau,
        seed=seed,
        sparse_degree=args.sparse_degree,
    )
    pops = initial_populations(sectors, args.n_max)
    x_edges = np.asarray(args.x_edges, dtype=float)
    target_probs = target_x_distribution(x_edges, args.ohmic_power)

    records: dict[str, list[float]] = {
        "energy": [],
        "area": [],
        "dimension_entropy": [],
        "effective_dimension": [],
        "jump_probability": [],
        "emitted_power": [],
        "conditional_omega": [],
        "spectrum_tv_to_thermal_x": [],
        "sector_uniformity_tv": [],
    }
    for _step in range(args.steps + 1):
        obs = observables(sectors, pops)
        spec = spectrum_observables(pops, transitions, x_edges, target_probs)
        row = {**obs, **spec, "sector_uniformity_tv": sector_uniformity(pops)}
        for key in records:
            records[key].append(float(row[key]))
        pops, _emitted = step_pops(sectors, pops, transitions.rates)
        apply_mixers(pops, mixers)

    result = {key: np.asarray(value, dtype=float) for key, value in records.items()}
    power = summarize_series(result["emitted_power"])
    jump = summarize_series(result["jump_probability"])
    omega = summarize_series(result["conditional_omega"])
    tv = summarize_series(result["spectrum_tv_to_thermal_x"])
    uniformity = summarize_series(result["sector_uniformity_tv"])
    return {
        "seed": seed,
        "operator": operator,
        "mass_law": mass_law,
        "dos": args.dos,
        "width_x": args.width_x,
        "mixing_type": mixing_type,
        "tau": tau,
        "sparse_degree": args.sparse_degree,
        "power_mid_over_early": power["mid_over_early"],
        "jump_mid_over_early": jump["mid_over_early"],
        "conditional_omega_mid_over_early": omega["mid_over_early"],
        "mean_spectrum_tv_to_thermal_x": float(np.nanmean(result["spectrum_tv_to_thermal_x"])),
        "mid_spectrum_tv_to_thermal_x": tv["mid"],
        "mean_sector_uniformity_tv": float(np.mean(result["sector_uniformity_tv"])),
        "mid_sector_uniformity_tv": uniformity["mid"],
        "initial_area": float(result["area"][0]),
        "final_area": float(result["area"][-1]),
        "initial_energy": float(result["energy"][0]),
        "final_energy": float(result["energy"][-1]),
        "final_dimension_entropy": float(result["dimension_entropy"][-1]),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run sector-Hamiltonian scrambling scan.")
    parser.add_argument("--q", type=int, default=2)
    parser.add_argument("--n-min", type=int, default=4)
    parser.add_argument("--n-max", type=int, default=10)
    parser.add_argument("--alpha", type=float, default=8.0)
    parser.add_argument("--operator-list", default="scrambled")
    parser.add_argument("--mass-laws", default="sqrt,linear")
    parser.add_argument("--dos", default="exponential")
    parser.add_argument("--width-x", type=float, default=4.0)
    parser.add_argument("--mixing-types", default="none,uniform,dense,expander,sparse")
    parser.add_argument("--tau-list", default="0.5,1,2,4,8")
    parser.add_argument("--sparse-degree", type=int, default=6)
    parser.add_argument("--pmax", type=float, default=0.08)
    parser.add_argument("--x-min", type=float, default=0.0)
    parser.add_argument("--x-max", type=float, default=8.0)
    parser.add_argument("--ohmic-power", type=float, default=1.0)
    parser.add_argument("--steps", type=int, default=80)
    parser.add_argument("--seeds", default="2468")
    parser.add_argument(
        "--x-edges",
        type=float,
        nargs="+",
        default=[0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 5.0, float("inf")],
    )
    parser.add_argument(
        "--summary-csv",
        type=pathlib.Path,
        default=DATADIR / "sector_hamiltonian_scrambling_summary.csv",
    )
    args = parser.parse_args(argv)

    seeds = parse_list(args.seeds, int)
    operators = parse_list(args.operator_list, str)
    mass_laws = parse_list(args.mass_laws, str)
    mixing_types = parse_list(args.mixing_types, str)
    taus = parse_list(args.tau_list, float)

    rows = []
    total = len(seeds) * len(operators) * len(mass_laws) * len(mixing_types) * len(taus)
    count = 0
    for seed in seeds:
        for operator in operators:
            for mass_law in mass_laws:
                for mixing_type in mixing_types:
                    tau_values = [0.0] if mixing_type in {"none", "uniform"} else taus
                    for tau in tau_values:
                        count += 1
                        print(
                            f"[sector-scramble] {count}/{total}: seed={seed} "
                            f"{operator} {mass_law} mix={mixing_type} tau={tau:g}",
                            flush=True,
                        )
                        try:
                            rows.append(
                                run_case(
                                    args,
                                    seed=seed,
                                    operator=operator,
                                    mass_law=mass_law,
                                    mixing_type=mixing_type,
                                    tau=tau,
                                )
                            )
                        except Exception as exc:
                            rows.append(
                                {
                                    "seed": seed,
                                    "operator": operator,
                                    "mass_law": mass_law,
                                    "mixing_type": mixing_type,
                                    "tau": tau,
                                    "error": str(exc),
                                }
                            )

    write_csv(args.summary_csv, rows)
    print(f"[sector-scramble] wrote {args.summary_csv}")
    good = [row for row in rows if "error" not in row]
    good.sort(
        key=lambda row: (
            row["mass_law"] != "sqrt",
            -float(row["power_mid_over_early"]),
            float(row["mean_spectrum_tv_to_thermal_x"]),
        )
    )
    print("best sqrt rows:")
    print("mix       tau    power   jump    omega   TV     sectorTV")
    for row in [r for r in good if r["mass_law"] == "sqrt"][:12]:
        print(
            f"{str(row['mixing_type']):9s} {float(row['tau']):5.2f} "
            f"{float(row['power_mid_over_early']):7.3f} "
            f"{float(row['jump_mid_over_early']):7.3f} "
            f"{float(row['conditional_omega_mid_over_early']):7.3f} "
            f"{float(row['mean_spectrum_tv_to_thermal_x']):7.3f} "
            f"{float(row['mean_sector_uniformity_tv']):9.3f}"
        )
    viable = [
        row
        for row in good
        if row["mass_law"] == "sqrt"
        and float(row["power_mid_over_early"]) > 1.0
        and float(row["mean_spectrum_tv_to_thermal_x"]) < 0.1
    ]
    print(f"sqrt cases with acceleration and TV < 0.1: {len(viable)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
