#!/usr/bin/env python3
"""Variable-particle Bose-Hubbard evaporation diagnostic.

This is the Step 3 test that fixes the conceptual problem with the fixed-N
probe. The core Hilbert space is a direct sum of Bose-Hubbard sectors with
different particle numbers, and emission is generated by annihilation operators

    b_i : H_N -> H_{N-1}.

The script evolves populations in the energy eigenbasis with a weak-coupling
particle-loss Markov map. It is a screening diagnostic, not yet a full
collision-Hamiltonian simulation.
"""
from __future__ import annotations

import argparse
import csv
import pathlib
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

try:
    import scipy.linalg as la
except Exception as exc:  # pragma: no cover
    raise SystemExit(f"SciPy is required: {exc}")

from scan_bose_hubbard_dos import DATADIR, build_bose_hubbard


@dataclass(frozen=True)
class Sector:
    n: int
    basis: list[tuple[int, ...]]
    evals_internal: NDArray[np.float64]
    evecs: NDArray[np.float64]

    @property
    def dim(self) -> int:
        return len(self.evals_internal)


def parse_list(value: str, kind):
    return [kind(part.strip()) for part in value.split(",") if part.strip()]


def build_sectors(args: argparse.Namespace, seed: int) -> dict[int, Sector]:
    sectors = {}
    for n in range(args.n_min, args.n_max + 1):
        h, basis = build_bose_hubbard(
            sites=args.sites,
            particles=n,
            geometry=args.geometry,
            j=args.j,
            u=args.u,
            v_nn=args.v_nn,
            j_inter=args.j_inter,
            disorder=args.disorder,
            seed=seed,
        )
        evals, evecs = la.eigh(h)
        sectors[n] = Sector(n=n, basis=basis, evals_internal=evals, evecs=evecs)
    return sectors


def annihilation_ops(
    higher: Sector,
    lower: Sector,
) -> list[NDArray[np.float64]]:
    sites = len(higher.basis[0])
    lower_index = {state: idx for idx, state in enumerate(lower.basis)}
    ops = []
    for site in range(sites):
        op = np.zeros((lower.dim, higher.dim), dtype=float)
        for col, state in enumerate(higher.basis):
            occupancy = state[site]
            if occupancy <= 0:
                continue
            lowered = list(state)
            lowered[site] -= 1
            row = lower_index[tuple(lowered)]
            op[row, col] = np.sqrt(float(occupancy))
        ops.append(op)
    return ops


def build_jump_maps(
    sectors: dict[int, Sector],
    mu: float,
    pmax: float,
    min_gap: float,
    max_gap: float,
    ohmic_power: float,
) -> tuple[dict[int, NDArray[np.float64]], dict[int, NDArray[np.float64]]]:
    raw_maps: dict[int, NDArray[np.float64]] = {}
    omega_maps: dict[int, NDArray[np.float64]] = {}

    for n in sorted(sectors):
        if n - 1 not in sectors:
            continue
        high = sectors[n]
        low = sectors[n - 1]
        e_high = mu * n + high.evals_internal
        e_low = mu * (n - 1) + low.evals_internal
        omega = e_high[None, :] - e_low[:, None]
        mask = (omega >= min_gap) & (omega <= max_gap)
        weights = np.where(mask, np.maximum(omega, 0.0) ** ohmic_power, 0.0)
        rates = np.zeros((low.dim, high.dim), dtype=float)
        for op in annihilation_ops(high, low):
            op_e = low.evecs.T @ op @ high.evecs
            rates += (np.abs(op_e) ** 2) * weights
        raw_maps[n] = rates
        omega_maps[n] = omega

    max_col = 0.0
    for rates in raw_maps.values():
        if rates.size:
            max_col = max(max_col, float(np.max(np.sum(rates, axis=0))))
    if max_col <= 0.0:
        raise ValueError("all particle-loss transition rates vanished")

    jump_maps = {n: rates * (pmax / max_col) for n, rates in raw_maps.items()}
    return jump_maps, omega_maps


def initial_populations(
    sectors: dict[int, Sector],
    n_max: int,
    e_min: float,
    e_max: float,
) -> dict[int, NDArray[np.float64]]:
    pops = {n: np.zeros(sector.dim, dtype=float) for n, sector in sectors.items()}
    evals = sectors[n_max].evals_internal
    mask = (evals >= e_min) & (evals <= e_max)
    if not np.any(mask):
        raise ValueError(f"initial N={n_max} window has no states: [{e_min}, {e_max}]")
    pops[n_max][mask] = 1.0 / float(np.sum(mask))
    return pops


def population_observables(
    sectors: dict[int, Sector],
    pops: dict[int, NDArray[np.float64]],
    mu: float,
) -> dict[str, float]:
    energy = 0.0
    internal_energy = 0.0
    particles = 0.0
    purity = 0.0
    shannon = 0.0
    sector_probs = {}
    for n, pop in pops.items():
        sector = sectors[n]
        p_sector = float(np.sum(pop))
        sector_probs[n] = p_sector
        energy += float(pop @ (mu * n + sector.evals_internal))
        internal_energy += float(pop @ sector.evals_internal)
        particles += n * p_sector
        purity += float(pop @ pop)
        positive = pop[pop > 0.0]
        shannon -= float(np.sum(positive * np.log(positive)))
    return {
        "energy": energy,
        "internal_energy": internal_energy,
        "particles": particles,
        "renyi2_core": -float(np.log(max(purity, 1e-300))),
        "shannon_core": shannon,
        **{f"sector_prob_N{n}": p for n, p in sector_probs.items()},
    }


def step_populations(
    sectors: dict[int, Sector],
    pops: dict[int, NDArray[np.float64]],
    jump_maps: dict[int, NDArray[np.float64]],
) -> tuple[dict[int, NDArray[np.float64]], float]:
    next_pops = {n: pop.copy() for n, pop in pops.items()}
    emitted_probability = 0.0

    for n, jump in jump_maps.items():
        pop = pops[n]
        colsum = np.sum(jump, axis=0)
        leaving = colsum * pop
        emitted_probability += float(np.sum(leaving))
        next_pops[n] -= leaving
        next_pops[n - 1] += jump @ pop

    total = sum(float(np.sum(pop)) for pop in next_pops.values())
    if total <= 0.0:
        raise FloatingPointError("population norm vanished")
    for n in next_pops:
        next_pops[n] = np.maximum(next_pops[n], 0.0) / total
    return next_pops, emitted_probability / total


def run_with_sectors(
    args: argparse.Namespace,
    sectors: dict[int, Sector],
    mu: float,
    max_gap: float,
    initial: tuple[float, float],
):
    jump_maps, omega_maps = build_jump_maps(
        sectors,
        mu=mu,
        pmax=args.pmax,
        min_gap=args.min_gap,
        max_gap=max_gap,
        ohmic_power=args.ohmic_power,
    )
    pops = initial_populations(sectors, args.n_max, initial[0], initial[1])

    records: dict[str, list[float]] = {
        "energy": [],
        "internal_energy": [],
        "particles": [],
        "renyi2_core": [],
        "shannon_core": [],
        "emitted_power": [],
        "emitted_probability": [],
    }
    for n in sectors:
        records[f"sector_prob_N{n}"] = []

    previous_energy = None
    for step in range(args.steps + 1):
        obs = population_observables(sectors, pops, mu)
        for key in records:
            if key == "emitted_power":
                records[key].append(0.0 if previous_energy is None else previous_energy - obs["energy"])
            elif key == "emitted_probability":
                continue
            else:
                records[key].append(float(obs.get(key, 0.0)))

        if step < args.steps:
            previous_energy = obs["energy"]
            pops, emitted = step_populations(sectors, pops, jump_maps)
            records["emitted_probability"].append(emitted)

    records["emitted_probability"].append(0.0)
    arrays = {key: np.asarray(value) for key, value in records.items()}
    dimensions = np.asarray([sectors[n].dim for n in sorted(sectors)], dtype=int)
    particle_numbers = np.asarray(sorted(sectors), dtype=int)
    max_jump_probability = max(float(np.max(np.sum(jump, axis=0))) for jump in jump_maps.values())
    return {
        **arrays,
        "dimensions": dimensions,
        "particle_numbers": particle_numbers,
        "max_jump_probability": np.asarray(max_jump_probability),
        "initial_state_count": np.asarray(int(np.sum((sectors[args.n_max].evals_internal >= initial[0]) & (sectors[args.n_max].evals_internal <= initial[1])))),
        "sector_internal_min": np.asarray([float(np.min(sectors[n].evals_internal)) for n in sorted(sectors)]),
        "sector_internal_max": np.asarray([float(np.max(sectors[n].evals_internal)) for n in sorted(sectors)]),
    }


def run_one(args: argparse.Namespace, seed: int, mu: float, max_gap: float, initial: tuple[float, float]):
    sectors = build_sectors(args, seed)
    return run_with_sectors(args, sectors, mu, max_gap, initial)


def summarize(result: dict[str, NDArray[np.float64]]) -> dict[str, float]:
    power = result["emitted_power"][1:]
    third = max(2, len(power) // 3)
    early = power[:third]
    mid = power[third : max(third + 1, 2 * len(power) // 3)]
    late = power[max(third + 1, 2 * len(power) // 3) :]
    s2 = result["renyi2_core"]
    return {
        "initial_energy": float(result["energy"][0]),
        "final_energy": float(result["energy"][-1]),
        "initial_particles": float(result["particles"][0]),
        "final_particles": float(result["particles"][-1]),
        "mean_power_early": float(np.mean(early)),
        "mean_power_mid": float(np.mean(mid)),
        "mean_power_late": float(np.mean(late)) if len(late) else float("nan"),
        "accel_ratio_mid_over_early": float(np.mean(mid) / max(np.mean(early), 1e-300)),
        "peak_renyi2_core": float(np.max(s2)),
        "peak_renyi2_step": float(np.argmax(s2)),
        "mean_emitted_probability": float(np.mean(result["emitted_probability"][:-1])),
        "max_jump_probability": float(result["max_jump_probability"]),
        "initial_state_count": float(result["initial_state_count"]),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run variable-N Bose-Hubbard evaporation diagnostic.")
    parser.add_argument("--sites", type=int, default=6)
    parser.add_argument("--n-max", type=int, default=8)
    parser.add_argument("--n-min", type=int, default=3)
    parser.add_argument("--geometry", default="ring")
    parser.add_argument("--j", type=float, default=0.5)
    parser.add_argument("--u", type=float, default=-1.0)
    parser.add_argument("--v-nn", type=float, default=-0.2)
    parser.add_argument("--j-inter", type=float, default=0.2)
    parser.add_argument("--disorder", type=float, default=0.02)
    parser.add_argument("--mu-list", default="4,6,8,10,12")
    parser.add_argument("--max-gap-list", default="2,4,8,12")
    parser.add_argument("--initial-windows", default="-18.5:-17,-20:-18,-21:-19,-22:-20")
    parser.add_argument("--pmax", type=float, default=0.08)
    parser.add_argument("--min-gap", type=float, default=0.05)
    parser.add_argument("--ohmic-power", type=float, default=1.0)
    parser.add_argument("--steps", type=int, default=80)
    parser.add_argument("--seeds", type=int, default=2)
    parser.add_argument("--seed", type=int, default=2468)
    parser.add_argument(
        "--output-csv",
        type=pathlib.Path,
        default=DATADIR / "variable_n_bose_hubbard_evaporation_scan.csv",
    )
    parser.add_argument(
        "--output-npz",
        type=pathlib.Path,
        default=DATADIR / "variable_n_bose_hubbard_evaporation_best.npz",
    )
    args = parser.parse_args(argv)

    mu_values = parse_list(args.mu_list, float)
    max_gap_values = parse_list(args.max_gap_list, float)
    initial_windows = []
    for item in args.initial_windows.split(","):
        lo, hi = item.split(":")
        initial_windows.append((float(lo), float(hi)))

    rows = []
    best = None
    best_payload = None
    total = len(mu_values) * len(max_gap_values) * len(initial_windows) * args.seeds
    count = 0

    for seed_offset in range(args.seeds):
        seed = args.seed + seed_offset
        print(f"[varN-BH] diagonalizing sectors for seed={seed}", flush=True)
        sectors = build_sectors(args, seed)
        dims = " ".join(f"N{n}:{sectors[n].dim}" for n in sorted(sectors))
        print(f"[varN-BH] sector dimensions {dims}", flush=True)
        for mu in mu_values:
            for max_gap in max_gap_values:
                try:
                    jump_maps, _ = build_jump_maps(
                        sectors,
                        mu=mu,
                        pmax=args.pmax,
                        min_gap=args.min_gap,
                        max_gap=max_gap,
                        ohmic_power=args.ohmic_power,
                    )
                except Exception as exc:
                    jump_maps = None
                    jump_error = str(exc)
                for initial in initial_windows:
                    count += 1
                    print(
                        f"[varN-BH] {count}/{total}: seed={seed} mu={mu:g} "
                        f"max_gap={max_gap:g} init=[{initial[0]:g},{initial[1]:g}]",
                        flush=True,
                    )
                    try:
                        if jump_maps is None:
                            raise ValueError(jump_error)
                        pops = initial_populations(sectors, args.n_max, initial[0], initial[1])

                        records: dict[str, list[float]] = {
                            "energy": [],
                            "internal_energy": [],
                            "particles": [],
                            "renyi2_core": [],
                            "shannon_core": [],
                            "emitted_power": [],
                            "emitted_probability": [],
                        }
                        for n in sectors:
                            records[f"sector_prob_N{n}"] = []

                        previous_energy = None
                        for step in range(args.steps + 1):
                            obs = population_observables(sectors, pops, mu)
                            for key in records:
                                if key == "emitted_power":
                                    records[key].append(0.0 if previous_energy is None else previous_energy - obs["energy"])
                                elif key == "emitted_probability":
                                    continue
                                else:
                                    records[key].append(float(obs.get(key, 0.0)))

                            if step < args.steps:
                                previous_energy = obs["energy"]
                                pops, emitted = step_populations(sectors, pops, jump_maps)
                                records["emitted_probability"].append(emitted)

                        records["emitted_probability"].append(0.0)
                        result = {key: np.asarray(value) for key, value in records.items()}
                        result.update(
                            {
                                "dimensions": np.asarray([sectors[n].dim for n in sorted(sectors)], dtype=int),
                                "particle_numbers": np.asarray(sorted(sectors), dtype=int),
                                "max_jump_probability": np.asarray(
                                    max(float(np.max(np.sum(jump, axis=0))) for jump in jump_maps.values())
                                ),
                                "initial_state_count": np.asarray(
                                    int(
                                        np.sum(
                                            (sectors[args.n_max].evals_internal >= initial[0])
                                            & (sectors[args.n_max].evals_internal <= initial[1])
                                        )
                                    )
                                ),
                                "sector_internal_min": np.asarray(
                                    [float(np.min(sectors[n].evals_internal)) for n in sorted(sectors)]
                                ),
                                "sector_internal_max": np.asarray(
                                    [float(np.max(sectors[n].evals_internal)) for n in sorted(sectors)]
                                ),
                            }
                        )
                        summary = summarize(result)
                        row = {
                            "seed": seed,
                            "mu": mu,
                            "max_gap": max_gap,
                            "initial_e_min": initial[0],
                            "initial_e_max": initial[1],
                            **summary,
                        }
                        if (
                            best is None
                            or (
                                summary["accel_ratio_mid_over_early"],
                                summary["mean_power_mid"],
                            )
                            > (
                                best["accel_ratio_mid_over_early"],
                                best["mean_power_mid"],
                            )
                        ):
                            best = row
                            best_payload = (result, row)
                    except Exception as exc:
                        row = {
                            "seed": seed,
                            "mu": mu,
                            "max_gap": max_gap,
                            "initial_e_min": initial[0],
                            "initial_e_max": initial[1],
                            "error": str(exc),
                        }
                    rows.append(row)

    fieldnames = sorted({key for row in rows for key in row})
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.output_csv.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"[varN-BH] wrote {args.output_csv}")

    if best_payload is not None:
        result, row = best_payload
        np.savez(
            args.output_npz,
            **{key: value for key, value in vars(args).items() if key not in {"output_csv", "output_npz"}},
            **result,
            **{f"summary_{key}": value for key, value in row.items() if isinstance(value, (int, float))},
        )
        print(f"[varN-BH] wrote {args.output_npz}")
        print("[varN-BH] best")
        for key in sorted(row):
            if key != "error":
                print(f"  {key}: {row[key]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
