#!/usr/bin/env python3
"""
Figure generation pipeline.
- Generates figures as PDFs into the LaTeX folder with expected filenames.
- Skips gracefully if dependencies are missing (so LaTeX build still works).
- Embeds Git commit hash in PDF metadata for provenance when available.
"""
from __future__ import annotations

import argparse
import math
import os
import pathlib
import subprocess
import sys
from typing import Callable, Dict


HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent


def _import_matplotlib():
    try:
        import matplotlib
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception as exc:
        print(f"[figs] matplotlib/numpy not available: {exc}")
        return None, None, None
    # Reasonable defaults for LaTeX-friendly styling
    matplotlib.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.grid": True,
        "axes.spines.top": False,
        "axes.spines.right": False,
    })
    return matplotlib, plt, np


def _git_describe() -> str | None:
    try:
        out = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=str(PROJECT))
        return out.decode().strip()
    except Exception:
        return None


def _save_pdf(fig, outpath: pathlib.Path, title: str):
    meta = {"Title": title}
    commit = _git_describe()
    if commit:
        meta["Subject"] = f"Generated by figs/generate.py @ {commit}"
    try:
        fig.savefig(outpath, bbox_inches="tight", metadata=meta)
        print(f"[figs] wrote {outpath.relative_to(PROJECT)}")
    finally:
        pass


def gen_p_of_e(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    # Prefer simulation data when available
    spectral = PROJECT / "sim" / "data" / "spectral.npz"
    if spectral.exists():
        dat = np.load(spectral)
        E = dat["E_centers"].astype(float)
        wstar = dat["omega_star"].astype(float)
        mask = np.isfinite(wstar) & (wstar > 0)
        E = E[mask]
        wstar = wstar[mask]
        # Ohmic in-band: J(ω) ∝ ω
        J = wstar
        X = (wstar * J)[:, None]
        y = (1.0 / (E**2))  # expected scaling guide
        # Calibrate beta by least squares so that beta * (w*J) ~ 1/E^2
        beta = float((X.T @ y) / (X.T @ X))
        Pn = beta * (wstar * J)
        # Slope check on log-log: expect ~ -2
        s = (np.polyfit(np.log(E[m2]), np.log(Pn[m2]), 1)[0] if (m2:=np.isfinite(E) & np.isfinite(Pn) & (E>0) & (Pn>0)).sum()>3 else float('nan'))
        if abs(s + 2.0) > 0.3:
            print(f"[check] P(E) slope deviates from -2: {s:.2f}")
    else:
        # Synthetic P(E) ~ beta / E^2 with small multiplicative noise
        beta = 1.0
        E = np.geomspace(1.0, 10.0, 40)
        P = beta / E**2
        noise = np.random.default_rng(1).lognormal(mean=0.0, sigma=0.05, size=E.shape)
        Pn = P * noise

    import matplotlib.gridspec as gridspec
    fig = plt.figure(figsize=(3.6, 3.0))
    gs = gridspec.GridSpec(2, 1, height_ratios=[3, 1], hspace=0.1)
    ax = fig.add_subplot(gs[0])
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.scatter(E, Pn, s=12, label="data")
    ax.plot(E, P, color="C1", label=r"$\propto E^{-2}$")
    ax.set_xlabel("E")
    ax.set_ylabel("P(E)")
    ax.legend(frameon=False)
    # Residuals in log space
    axr = fig.add_subplot(gs[1], sharex=ax)
    resid = np.log(Pn) - np.log(P)
    axr.axhline(0, color="k", lw=0.8)
    axr.plot(E, resid, color="C2")
    axr.set_ylabel("resid")
    axr.set_xlabel("E")
    for label in axr.get_xticklabels():
        label.set_rotation(0)
    _save_pdf(fig, output, "P(E) calibration")
    plt.close(fig)
    return True


def gen_e_of_t(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    spectral = PROJECT / "sim" / "data" / "spectral.npz"
    if spectral.exists():
        dat = np.load(spectral)
        Egrid = dat["E_centers"].astype(float)
        wstar = dat["omega_star"].astype(float)
        mask = np.isfinite(wstar) & (wstar > 0)
        Egrid = Egrid[mask]
        wstar = wstar[mask]
        # Fit beta as in gen_p_of_e
        J = wstar
        X = (wstar * J)[:, None]
        y = (1.0 / (Egrid**2))
        beta = float((X.T @ y) / (X.T @ X))
        # Numerical integration of dE/dt = - beta * w*J
        order = np.argsort(Egrid)[::-1]  # high to low energy
        E_sorted = Egrid[order]
        P_sorted = beta * (wstar[order] * J[order])
        # integrate t(E) = ∫ -dE / P(E)
        t = [0.0]
        for i in range(1, len(E_sorted)):
            dE = E_sorted[i] - E_sorted[i-1]
            Pmid = 0.5 * (P_sorted[i] + P_sorted[i-1])
            dt = -dE / max(Pmid, 1e-12)
            t.append(t[-1] + dt)
        t = np.array(t)
        E_num = E_sorted
        # Analytic overlay using E(t) = (E0^3 - 3 beta t)^{1/3}
        E0 = float(E_sorted[0])
        E_ana = (E0**3 - 3.0 * beta * t) ** (1.0 / 3.0)
        En = E_num
        E = E_ana
    else:
        beta = 1.0
        E0 = 10.0
        t = np.linspace(0.0, (E0**3) / (3 * beta) * 0.9, 60)
        E = (E0**3 - 3 * beta * t) ** (1.0 / 3.0)
        rng = np.random.default_rng(2)
        En = E * (1 + rng.normal(0.0, 0.01, size=E.shape))

    import matplotlib.gridspec as gridspec
    fig = plt.figure(figsize=(3.6, 3.0))
    gs = gridspec.GridSpec(2, 1, height_ratios=[3, 1], hspace=0.1)
    ax = fig.add_subplot(gs[0])
    ax.plot(t, E, color="C1", label="prediction")
    ax.scatter(t, En, s=10, color="C0", label="data")
    ax.set_xlabel("t")
    ax.set_ylabel("E(t)")
    ax.legend(frameon=False)
    # Residuals
    axr = fig.add_subplot(gs[1], sharex=ax)
    axr.axhline(0, color="k", lw=0.8)
    axr.plot(t, En - E, color="C2")
    axr.set_ylabel("resid")
    axr.set_xlabel("t")
    _save_pdf(fig, output, "E(t) overlay")
    plt.close(fig)
    return True


TargetGen = Callable[[pathlib.Path], bool]


def gen_s_of_e(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    thermo = PROJECT / "sim" / "data" / "thermo.npz"
    if thermo.exists():
        dat = np.load(thermo)
        E = dat["E_centers"].astype(float)
        S2 = dat["S"].astype(float)
        # Estimate a window width for highlighting
        E0 = float(E[len(E)//2])
        w = (E[-1] - E[0]) / (len(E))
    else:
        # Construct an S(E) with a convex intruder window
        E = np.linspace(1.0, 10.0, 200)
        S = 2.0 * np.log(E) + 0.25 * E
        E0, w, amp = 5.0, 1.2, 0.35
        intruder = amp * np.exp(-0.5 * ((E - E0) / (0.45 * w)) ** 2) * (1 - ((E - E0) / w) ** 2)
        S2 = S + intruder
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(E, S2, label=r"$S(E)$")
    ax.set_xlabel("E")
    ax.set_ylabel("S(E)")
    # Highlight window
    ax.axvspan(E0 - w, E0 + w, color="orange", alpha=0.2, label="convex intruder")
    ax.legend(frameon=False)
    _save_pdf(fig, output, "S(E) with convex intruder")
    plt.close(fig)
    return True


def gen_t_of_e(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    thermo = PROJECT / "sim" / "data" / "thermo.npz"
    if thermo.exists():
        dat = np.load(thermo)
        E = dat["E_centers"].astype(float)
        T = dat["T_mu"].astype(float)
    else:
        E = np.linspace(1.0, 10.0, 120)
        T = 1.0 / E
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(E, T, label=r"$T_{\mu}(E) \propto 1/E$")
    ax.set_xlabel("E")
    ax.set_ylabel(r"$T_{\mu}(E)$")
    _save_pdf(fig, output, "Microcanonical temperature vs E")
    plt.close(fig)
    return True


def gen_j_of_w(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    w = np.linspace(0.0, 6.0, 200)
    # Ohmic in-band between [1.5, 4.5]
    J = 0.05 * w
    band_lo, band_hi = 1.5, 4.5
    # Suppress out-of-band
    J[w < band_lo] *= np.exp(-((band_lo - w[w < band_lo])**2))
    J[w > band_hi] *= np.exp(-((w[w > band_hi] - band_hi)**2))
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(w, J, color="C0")
    ax.axvspan(band_lo, band_hi, color="green", alpha=0.15, label="in-band Ohmic")
    ax.set_xlabel(r"$\omega$")
    ax.set_ylabel(r"$J(\omega)$")
    ax.legend(frameon=False)
    _save_pdf(fig, output, "In-band Ohmic spectral density")
    plt.close(fig)
    return True


def gen_omega_star(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    spectral = PROJECT / "sim" / "data" / "spectral.npz"
    if spectral.exists():
        dat = np.load(spectral)
        E = dat["E_centers"].astype(float)
        wobs = dat["omega_star"].astype(float)
        mask = np.isfinite(wobs) & (wobs > 0)
        E = E[mask]; wobs = wobs[mask]
        # Slope check on log-log: expect ~ -1
        s = (np.polyfit(np.log(E[mask2]), np.log(wobs[mask2]), 1)[0] if (mask2:=np.isfinite(E) & np.isfinite(wobs) & (E>0) & (wobs>0)).sum()>3 else float('nan'))
        if abs(s + 1.0) > 0.3:
            print(f"[check] omega_star slope deviates from -1: {s:.2f}")
        wstar = 1.0 / E  # guide line
    else:
        E = np.geomspace(1.0, 10.0, 40)
        wstar = 1.2 / E
        rng = np.random.default_rng(3)
        wobs = wstar * (1 + rng.normal(0.0, 0.03, size=E.shape))
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.scatter(E, wobs, s=14, label="data")
    ax.plot(E, wstar, color="C1", label=r"$\propto E^{-1}$")
    ax.set_xlabel("E")
    ax.set_ylabel(r"$\omega_*(E)$")
    ax.legend(frameon=False)
    _save_pdf(fig, output, r"omega*(E) vs E")
    plt.close(fig)
    return True


def gen_kappa_of_e(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    thermo = PROJECT / "sim" / "data" / "thermo.npz"
    if thermo.exists():
        dat = np.load(thermo)
        E = dat["E_centers"].astype(float)
        T = dat["T_mu"].astype(float)
        kappa = T  # proportional (units suppressed)
        kobs = kappa
    else:
        E = np.geomspace(1.0, 10.0, 40)
        kappa = 1.8 / E
        rng = np.random.default_rng(4)
        kobs = kappa * (1 + rng.normal(0.0, 0.03, size=E.shape))
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(1.0 / E, kappa, color="C1", label="prediction")
    ax.scatter(1.0 / E, kobs, s=12, color="C0", label="data")
    ax.set_xlabel(r"$1/E$")
    ax.set_ylabel(r"$\kappa(E)$")
    ax.legend(frameon=False)
    _save_pdf(fig, output, "kappa vs 1/E")
    plt.close(fig)
    return True


def gen_page_curve(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    t = np.linspace(0.0, 1.0, 150)
    # Smooth rise then fall
    S2 = 1.6 * (1 - np.exp(-6 * t)) * np.exp(-2.0 * np.maximum(0, t - 0.55))
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(t, S2, color="C0")
    ax.axvspan(0.0, 0.35, color="gray", alpha=0.15, label="CP-divisible window")
    ax.set_xlabel("t")
    ax.set_ylabel(r"$S^{(2)}_{\rm rad}(t)$")
    ax.legend(frameon=False)
    _save_pdf(fig, output, "Renyi-2 Page-like curve")
    plt.close(fig)
    return True


def gen_distinguishability(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    t = np.linspace(0.0, 1.0, 120)
    D = 0.8 * np.exp(-6 * t) + 0.25 * np.maximum(0, t - 0.5)
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(t, D, color="C0")
    ax.set_xlabel("t")
    ax.set_ylabel(r"$D(t)$")
    _save_pdf(fig, output, "Microstate distinguishability")
    plt.close(fig)
    return True


def gen_blp(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    t = np.linspace(0.0, 1.0, 120)
    blp = 0.0 * t
    blp[t > 0.5] = 0.4 * (t[t > 0.5] - 0.5)
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(t, blp, color="C3")
    ax.set_xlabel("t")
    ax.set_ylabel("BLP proxy")
    _save_pdf(fig, output, "Non-Markovianity proxy")
    plt.close(fig)
    return True


def gen_overlay_em(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    # Overlay of two normalized spectra as a simple illustrative panel
    w = np.linspace(0.0, 6.0, 200)
    s1 = np.exp(-0.5 * ((w - 2.2) / 0.6) ** 2)
    s2 = 0.8 * np.exp(-0.5 * ((w - 3.2) / 0.7) ** 2)
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    ax.plot(w, s1 / s1.max(), label="core edge")
    ax.plot(w, s2 / s2.max(), label="channel")
    ax.set_xlabel(r"$\omega$")
    ax.set_ylabel("norm. power")
    ax.legend(frameon=False)
    _save_pdf(fig, output, "Overlay spectra")
    plt.close(fig)
    return True


def gen_contact_area(output: pathlib.Path):
    matplotlib, plt, np = _import_matplotlib()
    if matplotlib is None:
        return False
    spectral = PROJECT / "sim" / "data" / "spectral.npz"
    if not spectral.exists():
        print("[figs] contact-area: missing spectral data; generate sim/data first")
        return False
    dat = np.load(spectral)
    E = dat["E_centers"].astype(float)
    wstar = dat["omega_star"].astype(float)
    mask = np.isfinite(E) & np.isfinite(wstar) & (E > 0) & (wstar > 0)
    E = E[mask]
    wstar = wstar[mask]
    # Fit beta for M=1 using P ~ beta * w*J with J ~ w
    X = (wstar * wstar)[:, None]
    y = 1.0 / (E**2)
    denom = float(X.T @ X)
    beta = float((X.T @ y) / (denom if denom != 0 else 1.0))
    M_vals = [1, 2, 4]
    import matplotlib.gridspec as gridspec
    fig = plt.figure(figsize=(6.6, 3.0))
    gs = gridspec.GridSpec(1, 2, width_ratios=[1, 1], wspace=0.3)
    # Panel A: P(E) vs E for multiple M
    ax1 = fig.add_subplot(gs[0])
    ax1.set_xscale("log"); ax1.set_yscale("log")
    for M in M_vals:
        Pm = beta * M * (wstar * wstar)
        ax1.plot(E, Pm, label=f"M={M}")
    ax1.set_xlabel("E"); ax1.set_ylabel("P(E)")
    ax1.set_title("Power scales linearly with M")
    ax1.legend(frameon=False)
    # Panel B: E(t) collapse when time scaled by M
    ax2 = fig.add_subplot(gs[1])
    E0 = float(np.max(E))
    tgrid = np.linspace(0.0, 0.9 * (E0**3) / (3 * beta), 80)
    for M in M_vals:
        Et = (E0**3 - 3 * beta * M * tgrid) ** (1.0 / 3.0)
        ax2.plot(M * tgrid, Et, label=f"M={M}")
    ax2.set_xlabel("M t"); ax2.set_ylabel("E")
    ax2.set_title("E vs M t collapses")
    _save_pdf(fig, output, "Contact-area scaling: P and collapse")
    plt.close(fig)
    return True

def targets() -> Dict[str, TargetGen]:
    outdir = PROJECT
    return {
        # map target name to generator function + output filename
        "fig1a_SE": lambda out=outdir / "fig1a_SE.pdf": gen_s_of_e(out),
        "fig1b_T": lambda out=outdir / "fig1b_T.pdf": gen_t_of_e(out),
        "fig2a_J": lambda out=outdir / "fig2a_J.pdf": gen_j_of_w(out),
        "fig2b_omega_star": lambda out=outdir / "fig2b_omega_star.pdf": gen_omega_star(out),
        "fig3_P": lambda out=outdir / "fig3_P.pdf": gen_p_of_e(out),
        "fig4_Et": lambda out=outdir / "fig4_Et.pdf": gen_e_of_t(out),
        "fig5_kappa": lambda out=outdir / "fig5_kappa.pdf": gen_kappa_of_e(out),
        "fig6_pagecurve": lambda out=outdir / "fig6_pagecurve.pdf": gen_page_curve(out),
        "fig7a_distinguishability": lambda out=outdir / "fig7a_distinguishability.pdf": gen_distinguishability(out),
        "fig7b_BLP": lambda out=outdir / "fig7b_BLP.pdf": gen_blp(out),
        "fig8_overlay_EM": lambda out=outdir / "fig8_overlay_EM.pdf": gen_overlay_em(out),
        "fig9_contact_area": lambda out=outdir / "fig9_contact_area.pdf": gen_contact_area(out),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate paper figures")
    parser.add_argument("names", nargs="*", help="Figure names to generate (default: all)")
    parser.add_argument("--only-missing", dest="only_missing", action="store_true", help="Only generate if output is missing")
    args = parser.parse_args(argv)

    gens = targets()
    names = args.names or list(gens.keys())
    ok = True
    for name in names:
        if name not in gens:
            print(f"[figs] unknown figure: {name}")
            ok = False
            continue
        # For lambda closure, we cannot inspect output path easily; rely on missing check per known naming scheme
        if args.only_missing:
            # By convention, file name is <name>.pdf in PROJECT
            out = PROJECT / f"{name}.pdf"
            if out.exists():
                print(f"[figs] skip existing {out.relative_to(PROJECT)}")
                continue
        try:
            res = gens[name]()
            ok = ok and bool(res)
        except Exception as exc:
            print(f"[figs] failed {name}: {exc}")
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())

