#!/usr/bin/env python3
r"""
Compute simple fit diagnostics from available sim/data and write a small
LaTeX snippet figs/metrics.tex that can be \\input in the paper.
Safe to run even if data is missing (no-op).
"""
from __future__ import annotations

import math
import pathlib
from typing import Dict

import numpy as np


HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent


def write_metrics(metrics: Dict[str, float | str]):
    try:
        out = HERE / "metrics.tex"
        lines = [
            "% Auto-generated by figs/metrics.py\n",
            "\\begin{tabular}{l l}\\hline\n",
        ]
        for k, v in metrics.items():
            k = k.replace("R^2","$R^2$").replace("beta","$\\beta$"); lines.append(f"{k} & {v} \\\\n")
        lines.append("\\hline\\end{tabular}\n")
        out.write_text("".join(lines), encoding="utf-8")
        print(f"[figs] wrote {out.relative_to(PROJECT)}")
    except Exception as exc:
        print(f"[figs] metrics write failed: {exc}")

def write_macros(metrics: Dict[str, float | str]):
    """Write LaTeX macros so captions can include key numbers."""
    try:
        mapping = {
            "P(E) slope (log-log)": "\\PEslope",
            "P(E) R^2": "\\PERtwo",
            "P(E) nRMSE": "\\PEnrmse",
            "beta (arb.)": "\\betaval",
            "kappa(E) slope (log-log)": "\\Kslopelog",
            "kappa R^2": "\\KRtwo",
            "E(t) nRMSE": "\\Etnrmse",
        }
        out = HERE / "metrics_macros.tex"
        lines = ["% Auto-generated by figs/metrics.py\n"]
        for k, macro in mapping.items():
            if k in metrics:
                val = metrics[k]
                lines.append(f"\\renewcommand{{{macro}}}{{{val}}}\n")
        out.write_text("".join(lines), encoding="utf-8")
        print(f"[figs] wrote {out.relative_to(PROJECT)}")
    except Exception as exc:
        print(f"[figs] macro write failed: {exc}")


def main():
    spectral = PROJECT / "sim" / "data" / "spectral.npz"
    thermo = PROJECT / "sim" / "data" / "thermo.npz"
    metrics: Dict[str, float | str] = {}

    # P(E) diagnostics if spectral available
    if spectral.exists():
        dat = np.load(spectral)
        E = dat["E_centers"].astype(float)
        wstar = dat["omega_star"].astype(float)
        mask = np.isfinite(E) & np.isfinite(wstar) & (E > 0) & (wstar > 0)
        E = E[mask]
        wstar = wstar[mask]
        J = wstar
        X = (wstar * J)[:, None]
        y = (1.0 / (E**2))
        denom = (X.T @ X).item()
        beta = (X.T @ y).item() / (denom if denom != 0 else 1.0)
        Pn = beta * (wstar * J)
        # log-log
        m2 = np.isfinite(Pn) & (Pn > 0)
        if m2.sum() > 3:
            Xlog = np.log(E[m2]); Ylog = np.log(Pn[m2])
            b, a = np.polyfit(Xlog, Ylog, 1)
            Yhat = a + b * Xlog
            ss_res = float(np.sum((Ylog - Yhat) ** 2))
            ss_tot = float(np.sum((Ylog - np.mean(Ylog)) ** 2))
            r2 = 1.0 - (ss_res / ss_tot if ss_tot != 0 else 0.0)
            nrmse = math.sqrt(ss_res / max(1, len(Ylog))) / max(1e-12, (np.max(Ylog) - np.min(Ylog)))
            metrics.update({
                "P(E) slope (log-log)": f"{b:.3f}",
                "P(E) R^2": f"{r2:.3f}",
                "P(E) nRMSE": f"{nrmse:.3f}",
                "beta (arb.)": f"{beta:.4g}",
            })

    # kappa(E) diagnostics if thermo available
    if thermo.exists():
        dat = np.load(thermo)
        E = dat["E_centers"].astype(float)
        kobs = dat["T_mu"].astype(float)  # proportional
        mask = np.isfinite(E) & np.isfinite(kobs) & (E > 0) & (kobs > 0)
        if mask.sum() > 3:
            Xlog = np.log(E[mask]); Ylog = np.log(kobs[mask])
            b, a = np.polyfit(Xlog, Ylog, 1)
            Yhat = a + b * Xlog
            ss_res = float(np.sum((Ylog - Yhat) ** 2))
            ss_tot = float(np.sum((Ylog - np.mean(Ylog)) ** 2))
            r2 = 1.0 - (ss_res / ss_tot if ss_tot != 0 else 0.0)
            metrics.update({"kappa(E) slope (log-log)": f"{b:.3f}", "kappa R^2": f"{r2:.3f}"})

    if metrics:
        write_metrics(metrics)
        write_macros(metrics)
    else:
        print("[figs] no data for metrics; skipping")


if __name__ == "__main__":
    main()
