"""Planar-cap check for the Alcubierre front endpoint.

If an open front-horizon patch is locally planar and transversely uniform,
v=v(x), then the 3+1 metric is the direct product of the 1+1 metric with a
flat transverse plane.  The positive-boost-weight Riemann components found in
the rounded case vanish on that patch.  This script records the local criterion
and the first terms that reappear at a rounded rim.
"""

from __future__ import annotations

from pathlib import Path


OUT = Path("output/sech")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "Planar-cap extension check",
        "",
        "Metric:",
        "  ds^2 = -dt^2 + [dx - v(x,y,z) dt]^2 + dy^2 + dz^2",
        "",
        "Local front generator data:",
        "  v=-1, v_x=-kappa, v_y=v_z=0",
        "  K = q partial_t, q = 1/[kappa(lambda_* - lambda)]",
        "",
        "Generic local PP-curvature components at the front generator:",
        "  R_KNKY = -v_xy q",
        "  R_KNKZ = -v_xz q",
        "  R_KYKY = v_yy q^2",
        "  R_KYKZ = v_yz q^2",
        "  R_KZKZ = v_zz q^2",
        "  R_KNKN = v_xx - kappa^2",
        "",
        "Planar transversely uniform cap:",
        "  v=v(x) on an open transverse disk",
        "  so v_xy=v_xz=v_yy=v_yz=v_zz=0 there.",
        "",
        "Result on the planar patch:",
        "  all q-divergent PP-Riemann components vanish",
        "  the remaining listed component R_KNKN=v_xx-kappa^2 is finite",
        "  the 3+1 metric is ds^2_1+1 + dy^2 + dz^2",
        "  hence a local 1+1 C^2 horizon extension lifts by direct product",
        "  across this open planar patch.",
        "",
        "Explicit near-horizon 1+1 chart:",
        "  Let s=x-x_H and v(s)=-1-kappa s+O(s^2).",
        "  Set U=exp(-kappa t), s=U V.",
        "  For the linear model v=-1-kappa s,",
        "    ds^2_1+1 = -2/kappa dU dV + U^2 dV^2,",
        "  which is regular at U=0.",
        "  Higher Taylor terms in v(s) enter as smooth functions of U V",
        "  and keep the local product metric C^2 if v is smooth with a simple",
        "  horizon zero.",
        "",
        "Bent-front metric check:",
        "  Let the front surface be x=F(Y,Z)+s, with the same s=U V and",
        "  v=-1-kappa s in the leading model.",
        "  Then dx=d(UV)+F_A dY^A and dt=-dU/(kappa U).",
        "  The metric contains",
        "    g_{U A} = -F_A/(kappa U) + O(U).",
        "  Therefore the regularized null chart smooth across the planar patch is",
        "  singular at any point whose transverse neighborhood contains F_A != 0.",
        "  At a rounded stationary generator F_A=0 but F_AB != 0, this appears as",
        "    g_{U A} ~ -F_AB Y^B/(kappa U),",
        "  the coordinate version of the PP-curvature obstruction.",
        "",
        "Rim criterion:",
        "  If the finite bubble leaves the planar patch, the local product",
        "  argument stops applying.  The rim of an open planar patch has no",
        "  ordinary open neighborhood on which F_A=0 unless the product structure",
        "  persists beyond the rim.  At any stationary front generator in the",
        "  transition region, a PP-curvature obstruction appears if either",
        "    v_AB != 0  (quadratic q^2 screen-tidal blow-up), or",
        "    v_xA != 0  (linear q mixed PP-curvature blow-up).",
        "  Points with v_A != 0 are not generated by the stationary Killing field.",
        "  The causal-geodesic check shows that they do not supply the",
        "  finite-parameter endpoint of the reduced axial diagram.",
        "  Thus a flat cap opens only a local product extension window.",
        "  A finite capped bubble cannot turn that window into a smooth",
        "  four-dimensional extension unless the product structure persists",
        "  on an open transverse neighborhood past the would-be rim.",
        "",
        "Interpretation:",
        "  The rounded-front calculation is one case.  The actual local",
        "  criterion is positive boost-weight curvature.  Convex curvature gives",
        "  q^2 terms; transverse variation of surface gravity gives q terms; a",
        "  locally product planar patch has neither.",
    ]
    (OUT / "front_planar_cap_extension.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
